#cloud-config
ssh_authorized_keys:
  - ssh-rsa yourkey
hostname: yourhostname
rancher:
  network:
    interfaces:
      eth0:
        address: yourip/28
        gateway: yourgateway
        mtu: 1500
        dhcp: false
    dns:
      nameservers:
        - yourdnsserver
        - yourdnsserver
